//Chris V


package org.usfirst.frc5112.Robot2016.subsystems;

import org.usfirst.frc5112.Robot2016.DualCANTalon;
import org.usfirst.frc5112.Robot2016.RobotMap;
import org.usfirst.frc5112.Robot2016.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DualCANTalon leftDriveMotor = RobotMap.driveTrainLeftDriveMotor;
    private final DualCANTalon rightDriveMotor = RobotMap.driveTrainRightDriveMotor;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void operate(double speed, double rotate) {
    	robotDrive.drive(speed, rotate);
    }
    
    public void stop(){
    	robotDrive.drive(0, 0);
    }
    
    public void forward(double speed) {
    	
    }
    
    public void reverse(double speed) {
    	
    }
    
    public void rotateCW(double rotationSpeed) {
    	
    }
    
    public void rotateCCW(double rotationSpeed) {
    	
    }


}
