// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5112.Robot2016;

import edu.wpi.first.wpilibj.BuiltInAccelerometer;
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static DualCANTalon driveTrainLeftDriveMotor;
	public static DualCANTalon driveTrainRightDriveMotor;
	public static RobotDrive driveTrainRobotDrive;
	public static SpeedController intakeIntakeBarMotor;
	public static SpeedController shooterFlywheelMotor;
	public static Servo hoodServo;
	public static MicrosoftLifeCam robotCamera;
	public static BuiltInAccelerometer accelerometer;
	public static PowerDistributionPanel pdp;

	public static void init() {
		driveTrainRightDriveMotor = new DualCANTalon(0, 1);

		driveTrainLeftDriveMotor = new DualCANTalon(2, 3);

		driveTrainRobotDrive = new RobotDrive(driveTrainLeftDriveMotor, driveTrainRightDriveMotor);

		driveTrainRobotDrive.setSafetyEnabled(true);
		driveTrainRobotDrive.setExpiration(0.1);
		driveTrainRobotDrive.setSensitivity(0.5);
		driveTrainRobotDrive.setMaxOutput(1.0);

		driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
		intakeIntakeBarMotor = new Jaguar(0);
		LiveWindow.addActuator("Intake", "Intake Bar Motor", (Jaguar) intakeIntakeBarMotor);

		shooterFlywheelMotor = new Jaguar(1);
		LiveWindow.addActuator("Shooter", "Flywheel Motor", (Jaguar) shooterFlywheelMotor);

		hoodServo = new Servo(3);

		robotCamera = new MicrosoftLifeCam("cam0");

		accelerometer = new BuiltInAccelerometer();

		pdp = new PowerDistributionPanel();

	}
}
